npcs:
  '54': Wes
  '3': Rosalie
  '69': Skrik
  '20': Chris
  '50': Tony
  '51': Bella
  '70': Agata

items:
  steak: COOKED_BEEF #Stek, quest-1 Wes
  
  potka_leczenia: "potion effects:instant_health:3:69 name:&c&lElixir_Herbanum lore:Lore_trzeba_zrobić;&2Quest_Reward;" #Potka, quest-2 Skrik
  list_do_chrisa: PAPER name:List_Dla_Chrisa lore:&2Quest_Item
  zloty_miecz: GOLDEN_SWORD
  ciastko: COOKIE

  # Lista produktow main quest 2 - Bella
  lista_produktow: WRITTEN_BOOK
    title:Lista_produktów
    author:Bella
    text:&2&lLista_produktów&r\n1x_mleko\n10x_pszenica\n8x_jajko\n4x_surowy_łosoś\n2x_surowy_kurczak\n1x_cukier\n3x_ziemniak\n4x_marchew
    lore:&2Quest_Item
  
  mleko: MILK_BUCKET
  pszenica: WHEAT
  jajko: EGG
  surowy_losos: SALMON
  surowy_kurczak: CHICKEN
  cukier: SUGAR
  ziemniak: POTATO
  marchew: CARROT

  # Main quest 2 - nagrody
  klucz_do_pokoju: NAME_TAG name:&lKlucz_do_pokoju lore:Klucz_otrzymany_od_karczmarza_Chrisa,;potrzebny_do_otwarcia_pokoju_w_jego_karczmie;&2Quest_Item
  pieczony_kurczak: COOKED_CHICKEN
  pieczony_schab: COOKED_PORKCHOP
  pieczony_krolik: COOKED_RABBIT
