npcs:
 '257': Daily
 '261': Weekly
 '262': Monthly

 '76': Paulina

items:
  OAK_LOG: OAK_LOG
  BREAD: BREAD
  COOKED_CHICKEN: COOKED_CHICKEN
  COOKED_BEEF: COOKED_BEEF
  BAKED_POTATO: BAKED_POTATO
  CARROT: CARROT
  COOKED_PORKCHOP: COOKED_PORKCHOP
  COOKIE: COOKIE
  IRON_INGOT: IRON_INGOT
  GOLD_INGOT: GOLD_INGOT
  COPPER_INGOT: COPPER_INGOT
  COOKED_MUTTON: COOKED_MUTTON
  CHARCOAL: CHARCOAL
  SPRUCE_LOG: SPRUCE_LOG
  BIRCH_LOG: BIRCH_LOG
  JUNGLE_LOG: JUNGLE_LOG
  ACACIA_LOG: ACACIA_LOG
  DARK_OAK_LOG: DARK_OAK_LOG
  CHERRY_LOG: CHERRY_LOG
  COBBLESTONE: COBBLESTONE
  DANDELION: DANDELION
  POPPY: POPPY
  RED_TULIP: RED_TULIP
  ORANGE_TULIP: ORANGE_TULIP
  WHITE_TULIP: WHITE_TULIP
  PINK_TULIP: PINK_TULIP
  LILAC: LILAC
  ROSE_BUSH: ROSE_BUSH
  SUNFLOWER: SUNFLOWER
  SAND: SAND
  GRAVEL: GRAVEL
  COAL: COAL
  RAW_IRON: RAW_IRON
  CHARCOAL: CHARCOAL
  INK_SAC: INK_SAC  
  SUGAR_CANE: SUGAR_CANE
  REDSTONE: REDSTONE
  DIRT: DIRT
  CLAY_BALL: CLAY_BALL
  POTATO: POTATO
  CARROT: CARROT
  BEETROOT: BEETROOT
  RAW_COPPER: RAW_COPPER
  LEATHER: LEATHER
  BEEF: BEEF
  CHICKEN: CHICKEN
  PORKCHOP: PORKCHOP
  MUTTON: MUTTON
  WHEAT_SEEDS: WHEAT_SEEDS
  BEETROOT_SEEDS: BEETROOT_SEEDS
  WHEAT: WHEAT
  CAKE: CAKE
  TUFF: TUFF
  BRICK: BRICK
  TORCH: TORCH
  WOODEN_BUTTON: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_BUTTON"
  WOODEN_FENCE: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_FENCE"
  WOODEN_FENCE_GATE: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_FENCE_GATE"
  WOODEN_STAIRS: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_STAIRS"
  WOODEN_SLAB: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_SLAB"
  WOODEN_DOOR: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_DOOR"
  WOODEN_TRAPDOOR: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_TRAPDOOR"
  WOODEN_PRESSURE_PLATE: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_PRESSURE_PLATE"
  WOODEN_BOAT: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_BOAT"
  WOODEN_SIGN: "(OAK|SPRUCE|BIRCH|JUNGLE|ACACIA|DARK_OAK|MANGROVE|CHERRY|BAMBOO)_SIGN"
  COBBLESTONE_STAIRS: COBBLESTONE_STAIRS
  COBBLESTONE_SLAB: COBBLESTONE_SLAB
  COBBLESTONE_WALL: COBBLESTONE_WALL
  COBBLED_DEEPSLATE_STAIRS: COBBLED_DEEPSLATE_STAIRS
  COBBLED_DEEPSLATE_SLAB: COBBLED_DEEPSLATE_SLAB
  COBBLED_DEEPSLATE_WALL: COBBLED_DEEPSLATE_WALL
  BRICK_STAIRS: BRICK_STAIRS
  BRICK_SLAB: BRICK_SLAB
  BRICK_WALL: BRICK_WALL
  BELL: BELL
  PISTON: PISTON
  ENCHANTING_TABLE: ENCHANTING_TABLE
  SNOWBALL: SNOWBALL
  CHEST: CHEST
  CRAFTING_TABLE: CRAFTING_TABLE
  COMPOSTER: COMPOSTER
  NOTE_BLOCK: NOTE_BLOCK
  IRON_TOOLS: "IRON_(SWORD|PICKAXE|HOE|AXE|SHOVEL)"
  IRON_SET1: "IRON_(HELMET|LEGGINGS)"
  IRON_SET2: "IRON_(CHESTPLATE|BOOTS)"
  SAND: SAND
  DEEPSLATE: DEEPSLATE 
  VINE: VINE
  COCOA_BEANS: COCOA_BEANS
  MELON_SLICE: MELON_SLICE
  PUMPKIN: PUMPKIN
  POTATO: POTATO
  CARROT: CARROT
  RABBIT: RABBIT
  SWEET_BERRIES: SWEET_BERRIES
  APPLE: APPLE
  PUMPKIN_SEEDS: PUMPKIN_SEEDS
  MELON_SEEDS: MELON_SEEDS
  BREAD: BREAD
  MOSSY_COBBLESTONE: MOSSY_COBBLESTONE
  LILY_PAD: LILY_PAD
  BROWN_MUSHROOM: BROWN_MUSHROOM
  RED_MUSHROOM: RED_MUSHROOM
  GOLDEN_APPLE: GOLDEN_APPLE
  IRON_TRAPDOOR: IRON_TRAPDOOR
  IRON_DOOR: IRON_DOOR
  ANVIL: ANVIL
  WRITABLE_BOOK: WRITABLE_BOOK
  RABBIT_STEW: RABBIT_STEW
  DIAMOND_TOOLS: "DIAMOND_(SWORD|PICKAXE|HOE|AXE|SHOVEL)"
  DIAMOND_SET: "DIAMOND_(HELMET|LEGGINGS|CHESTPLATE|BOOTS)"
  GUNPOWDER: GUNPOWDER
  BONE: BONE
  GLOW_INK_SAC: GLOW_INK_SAC
  RED_SAND: RED_SAND
  ENDER_PEARL: ENDER_PEARL
  COBWEB: COBWEB
  CALCITE: CALCITE
  STRING: STRING
  SMALL_AMETHYST_BUD: SMALL_AMETHYST_BUD
  OBSIDIAN: OBSIDIAN
  HONEYCOMB: HONEYCOMB
  TERRACOTTA: TERRACOTTA
  SPIDER_EYE: SPIDER_EYE
  HONEY_BOTTLE: HONEY_BOTTLE
  POISONOUS_POTATO: POISONOUS_POTATO
  GOLDEN_CARROT: GOLDEN_CARROT
  GOAT_HORN: GOAT_HORN
  SLIME_BLOCK: SLIME_BLOCK
  ROTTEN_FLESH: ROTTEN_FLESH
  RAIL: RAIL
  POWERED_RAIL: POWERED_RAIL
  ACTIVATOR_RAIL: ACTIVATOR_RAIL
  DETECTOR_RAIL: DETECTOR_RAIL
  CHAIN: CHAIN
  DRIED_KELP_BLOCK: DRIED_KELP_BLOCK
  CAMPFIRE: CAMPFIRE
  PAPER: PAPER
  DRIED_KELP: DRIED_KELP
  IRON_BARS: IRON_BARS
  PUMPKIN_PIE: PUMPKIN_PIE


  # Paulina
  lista_produktow_rybenka: WRITTEN_BOOK
    title:Lista_produktów_na_Rybeńkę
    author:Bella
    text:&2&lLista_produktów&r\n2x_cukier\n1x_surowy_łosoś\n4x_marchew\n1x_butelka_wody
    lore:&2Quest_Item
  lista_produktow_zupa_ogorkowa: WRITTEN_BOOK
    title:Lista_produktów_na_Zupę_Ogórkową
    author:Bella
    text:&2&lLista_produktów&r\n5x_morski_ogór\n2x_butelka_wody\n3x_burak\n1x_miska
    lore:&2Quest_Item
  lista_produktow_miodowe: WRITTEN_BOOK
    title:Lista_produktów_na_Miodowe
    author:Bella
    text:&2&lLista_produktów&r\n2x_butelka_miodu\n3x_cukier\n1x_butelka\n1x_kakao
    lore:&2Quest_Item
  lista_produktow_chleb_marchewkowy: WRITTEN_BOOK
    title:Lista_produktów_na_Chlebek
    author:Bella
    text:&2&lLista_produktów&r\n10x_marchew\n1x_cukier\n12x_pszenica
    lore:&2Quest_Item
  
  surowy_losos: SALMON
  marchew: CARROT
  cukier: SUGAR
  butelka_wody: POTION
  morski_ogor: SEA_PICKLE
  burak: BEETROOT
  miska: BOWL
  butelka_miodu: HONEY_BOTTLE
  butelka: GLASS_BOTTLE
  kakao: COCOA_BEANS
  pszenica: WHEAT

  rybenka: SWEET_BERRIES name:&lRybeńka lore:Łosoś_tak_soczysty,_że_aż_ślinka_cieknie!
  zupa_ogorkowa: SWEET_BERRIES name:&lZupa_Ogórkowa lore:Nic_dodać,_nic_ująć.
  miodowe: SWEET_BERRIES name:&lMiodowe_co_nie_co lore:Nie_zabieraj_tego_przedmiotu_do_lasu;wysokie_prawdopodobieństwo_ataku_niedźwiedzia!
  chlebek_marchewkowy: SWEET_BERRIES name:&lChlebek_Marchewkowy lore:Dalej_ciepły!