npcs:
  '17': Maxwell
  '4': Winston
  '239': KasynoLaxstad
  '240' : KasynoSkogmork
  '0' : SamouczekWejscie
  '241' : SamouczekWstep
  '254' : SamouczekPowrot
  '255' : SamouczekMiasta
  '244' : SamouczekSklepy
  '248' : SamouczekFarby
  '247' : SamouczekRangi
  '250' : SamouczekWaluta
  '253' : SamouczekWymiany
  '246' : SamouczekWalka
  '245' : SamouczekRynek
  '249' : SamouczekAukcje
  '252' : SamouczekTeleporty
  '251' : SamouczekZapros
  '256' : SamouczekQuesty
  '243' : SamouczekDzialki
  

items:
# Barmani
  Trunek: GLASS_BOTTLE
